import type { Language } from "../lib/db";
import type { DuesBackupErrorCode, DuesRestoreReason } from "../lib/due-backup";
import type { DuesLedgerErrorCode, DuesLedgerRestoreReason } from "../lib/dues-ledger-archive";

const text = (language: Language, en: string, hi: string, bn: string) =>
  language === "hi" ? hi : language === "bn" ? bn : en;

export function dueBackupCopy(language: Language) {
  return {
    title: text(language, "Backup & restore dues", "बाकी का बैकअप और रिस्टोर", "বাকি ব্যাকআপ ও ফিরিয়ে আনা"),
    helper: text(language, "Save every outstanding and paid-in-full due account with its complete bills, payments, allocations, returns, dates, times and running balances.", "हर बाकी और पूरा भुगतान वाले खाते को उसके पूरे बिल, पेमेंट, बँटवारे, वापसी, तारीख, समय और चलते बैलेंस सहित सेव करें।", "প্রতিটি বাকি ও সম্পূর্ণ পরিশোধিত হিসাবকে তার সব বিল, পেমেন্ট, বণ্টন, ফেরত, তারিখ, সময় ও চলতি ব্যালেন্সসহ সেভ করুন।"),
    balancesOnly: text(language, "New exports restore the original customer ledger history. Older MKDUES1 files remain supported as clearly marked balance-only imports.", "नए एक्सपोर्ट असली कस्टमर खाता हिस्ट्री रिस्टोर करते हैं। पुराने MKDUES1 फाइल साफ़ तौर पर बैलेंस-ओनली इम्पोर्ट के रूप में अभी भी चलेंगे।", "নতুন এক্সপোর্ট আসল ক্রেতা খাতার ইতিহাস ফিরিয়ে আনে। পুরোনো MKDUES1 ফাইল স্পষ্টভাবে শুধু-ব্যালেন্স ইমপোর্ট হিসেবে এখনও চলবে।"),
    privacy: text(language, "Private file: it contains customer contact details and debt balances. Share it only with someone you trust.", "निजी फाइल: इसमें कस्टमर की संपर्क जानकारी और बाकी रकम है। इसे सिर्फ भरोसेमंद व्यक्ति से शेयर करें।", "ব্যক্তিগত ফাইল: এতে ক্রেতার যোগাযোগের তথ্য ও বাকি টাকা আছে। শুধু বিশ্বস্ত ব্যক্তির সঙ্গে শেয়ার করুন।"),
    exportHeading: text(language, "Export complete due ledgers", "पूरे बाकी खाते एक्सपोर्ट करें", "সম্পূর্ণ বাকি খাতা এক্সপোর্ট করুন"),
    exportPdf: text(language, "PDF backup", "PDF बैकअप", "PDF ব্যাকআপ"),
    exportText: text(language, "Text backup", "टेक्स्ट बैकअप", "টেক্সট ব্যাকআপ"),
    importHeading: text(language, "Restore a backup", "बैकअप वापस लाएँ", "ব্যাকআপ ফিরিয়ে আনুন"),
    importFile: text(language, "Choose PDF or text backup", "PDF या टेक्स्ट बैकअप चुनें", "PDF বা টেক্সট ব্যাকআপ বাছুন"),
    importHelp: text(language, "Only a valid, integrity-checked Midori Kanjo-format dues-backup PDF or text file can be imported. Verify the source and every balance during review; nothing changes until confirmation.", "सिर्फ सही फॉर्मेट और इंटीग्रिटी-जाँचा हुआ Midori Kanjo बाकी-बैकअप PDF या टेक्स्ट इम्पोर्ट होगा। समीक्षा में सोर्स और हर बैलेंस जाँचें; पुष्टि तक कुछ नहीं बदलेगा।", "শুধু সঠিক ফরম্যাট ও ইন্টেগ্রিটি-যাচাই করা Midori Kanjo বাকি-ব্যাকআপ PDF বা টেক্সট ইমপোর্ট হবে। পর্যালোচনায় উৎস ও প্রতিটি ব্যালেন্স যাচাই করুন; নিশ্চিত করার আগে কিছু বদলাবে না।"),
    reading: text(language, "Reading backup…", "बैकअप पढ़ा जा रहा है…", "ব্যাকআপ পড়া হচ্ছে…"),
    review: text(language, "Review before restore", "रिस्टोर से पहले समीक्षा", "ফিরিয়ে আনার আগে পর্যালোচনা"),
    file: text(language, "File", "फाइल", "ফাইল"),
    source: text(language, "Source business", "सोर्स बिज़नेस", "উৎস ব্যবসা"),
    created: text(language, "Backup created", "बैकअप बना", "ব্যাকআপ তৈরি"),
    customers: text(language, "Customers", "कस्टमर", "ক্রেতা"),
    total: text(language, "Total backup due", "बैकअप की कुल बाकी", "ব্যাকআপের মোট বাকি"),
    transactions: text(language, "Transactions", "लेन-देन", "লেনদেন"),
    paidInFull: text(language, "Paid in full", "पूरा भुगतान", "সম্পূর্ণ পরিশোধ"),
    completeHistory: text(language, "Complete ledger history", "पूरा खाता इतिहास", "সম্পূর্ণ খাতার ইতিহাস"),
    legacyBalance: text(language, "Legacy balance-only backup", "पुराना बैलेंस-ओनली बैकअप", "পুরোনো শুধু-ব্যালেন্স ব্যাকআপ"),
    newCustomers: text(language, "New", "नए", "নতুন"),
    matchedCustomers: text(language, "Matched", "मिले हुए", "মিলেছে"),
    alreadyPresent: text(language, "Already present", "पहले से मौजूद", "আগেই আছে"),
    conflicts: text(language, "Conflicts", "टकराव", "দ্বন্দ্ব"),
    backupDue: text(language, "Backup due", "बैकअप की बाकी", "ব্যাকআপের বাকি"),
    currentDue: text(language, "Current due", "मौजूदा बाकी", "বর্তমান বাকি"),
    destination: text(language, "Destination account", "जिस खाते में जाएगा", "যে হিসাবে যাবে"),
    willRestore: text(language, "Will restore", "वापस आएगा", "ফিরিয়ে আনা হবে"),
    willCreate: text(language, "Create customer + due", "कस्टमर और बाकी बनाएँ", "ক্রেতা ও বাকি তৈরি"),
    willMatch: text(language, "Add to empty matched account", "मिले खाली खाते में जोड़ें", "মিলে যাওয়া খালি হিসাবে যোগ"),
    skipped: text(language, "No change", "कोई बदलाव नहीं", "কোনো পরিবর্তন নয়"),
    blocked: text(language, "Needs manual review", "हाथ से जाँच जरूरी", "নিজে দেখে মেলাতে হবে"),
    conflictHelp: text(language, "Restore is blocked because one or more customers already have different balances, history or ambiguous details. No rows will be imported until every conflict is resolved outside this backup.", "रिस्टोर रुका है क्योंकि एक या अधिक कस्टमर के अलग बैलेंस, पुरानी हिस्ट्री या अस्पष्ट डिटेल हैं। हर टकराव को बाहर ठीक किए बिना कोई रिकॉर्ड इम्पोर्ट नहीं होगा।", "এক বা একাধিক ক্রেতার আলাদা ব্যালেন্স, আগের ইতিহাস বা অস্পষ্ট তথ্য থাকায় ফিরিয়ে আনা বন্ধ আছে। সব দ্বন্দ্ব বাইরে ঠিক না করা পর্যন্ত কোনো রেকর্ড ইমপোর্ট হবে না।"),
    allAlready: text(language, "Nothing needs restoring. These balances are already present or this backup was imported before.", "कुछ भी वापस लाने की जरूरत नहीं है। ये बैलेंस पहले से मौजूद हैं या यह बैकअप पहले इम्पोर्ट हो चुका है।", "কিছুই ফিরিয়ে আনার দরকার নেই। এই ব্যালেন্স আগে থেকেই আছে অথবা ব্যাকআপটি আগে ইমপোর্ট হয়েছে।"),
    ownerNotice: text(language, "Owner Mode is required to commit financial balances.", "फाइनेंशियल बैलेंस इम्पोर्ट करने के लिए Owner Mode जरूरी है।", "আর্থিক ব্যালেন্স ফিরিয়ে আনতে Owner Mode দরকার।"),
    restoreButton: (count: number, amount: string, ownerMode: boolean) => text(
      language,
      `${ownerMode ? "Restore" : "Unlock & restore"} ${count} balances · ${amount}`,
      `${ownerMode ? "रिस्टोर करें" : "अनलॉक करके रिस्टोर करें"} ${count} बैलेंस · ${amount}`,
      `${ownerMode ? "ফিরিয়ে আনুন" : "আনলক করে ফিরিয়ে আনুন"} ${count} ব্যালেন্স · ${amount}`,
    ),
    restoring: text(language, "Restoring balances…", "बैलेंस रिस्टोर हो रहे हैं…", "ব্যালেন্স ফিরিয়ে আনা হচ্ছে…"),
    resultTitle: text(language, "Dues restored", "बाकी रकम रिस्टोर हुई", "বাকি টাকা ফিরিয়ে আনা হয়েছে"),
    resultHelp: text(language, "The selected customer histories were restored atomically. Complete-ledger files preserve their original bills, receipts, allocations, returns and timestamps; legacy files remain balance-only.", "चुनी हुई कस्टमर हिस्ट्री एक साथ रिस्टोर हुई। पूरा-खाता फाइल असली बिल, रसीद, बँटवारा, वापसी और समय सुरक्षित रखती है; पुरानी फाइल बैलेंस-ओनली रहती है।", "নির্বাচিত ক্রেতার ইতিহাস একসঙ্গে ফিরিয়ে আনা হয়েছে। সম্পূর্ণ-খাতা ফাইল আসল বিল, রসিদ, বণ্টন, ফেরত ও সময় সংরক্ষণ করে; পুরোনো ফাইল শুধু-ব্যালেন্স থাকে।"),
    imported: text(language, "Imported", "इम्पोर्ट हुआ", "ইমপোর্ট হয়েছে"),
    amount: text(language, "Amount", "रकम", "টাকা"),
    createdCustomers: text(language, "Customers created", "कस्टमर बने", "ক্রেতা তৈরি"),
    matched: text(language, "Existing customers matched", "मौजूदा कस्टमर मिले", "আগের ক্রেতা মিলেছে"),
    done: text(language, "Done", "हो गया", "সম্পন্ন"),
    showNext: (count: number) => text(language, `Show next ${count}`, `अगले ${count} दिखाएँ`, `পরের ${count}টি দেখান`),
    exportDone: (format: string, result: string) => text(language, `${format} dues backup ${result}.`, `${format} बाकी बैकअप ${result}।`, `${format} বাকি ব্যাকআপ ${result}।`),
    shared: text(language, "shared", "शेयर हो गया", "শেয়ার হয়েছে"),
    downloaded: text(language, "downloaded", "डाउनलोड हो गया", "ডাউনলোড হয়েছে"),
    exportFailed: text(language, "The dues backup could not be exported.", "बाकी बैकअप एक्सपोर्ट नहीं हो सका।", "বাকি ব্যাকআপ এক্সপোর্ট করা যায়নি।"),
    importFailed: text(language, "The balances could not be restored. Review the backup again.", "बैलेंस रिस्टोर नहीं हुए। बैकअप फिर से जाँचें।", "ব্যালেন্স ফিরিয়ে আনা যায়নি। ব্যাকআপ আবার দেখুন।"),
    close: text(language, "Close", "बंद करें", "বন্ধ করুন"),
    reason: (reason: DuesRestoreReason) => ({
      new_customer: text(language, "New customer", "नया कस्टमर", "নতুন ক্রেতা"),
      matched_empty_customer: text(language, "Unique empty account matched", "एक खाली खाता मिला", "একটি খালি হিসাব মিলেছে"),
      same_import_entry: text(language, "This due was already restored", "यह बाकी पहले रिस्टोर हुई", "এই বাকি আগেই ফিরিয়ে আনা হয়েছে"),
      same_balance_present: text(language, "The same balance is already present", "यही बैलेंस पहले से मौजूद है", "একই ব্যালেন্স আগে থেকেই আছে"),
      different_import_amount: text(language, "A different snapshot was already restored", "दूसरा स्नैपशॉट पहले रिस्टोर हुआ", "অন্য স্ন্যাপশট আগে ফিরিয়ে আনা হয়েছে"),
      existing_balance: text(language, "This account already has a different due", "इस खाते में अलग बाकी पहले से है", "এই হিসাবে অন্য বাকি আগে থেকেই আছে"),
      existing_history: text(language, "This settled account has earlier financial history", "इस चुकाए खाते में पुरानी फाइनेंशियल हिस्ट्री है", "এই মেটানো হিসাবে আগের আর্থিক ইতিহাস আছে"),
      ambiguous_identity: text(language, "Customer details match more than one account", "कस्टमर की डिटेल एक से ज्यादा खातों से मिलती है", "ক্রেতার তথ্য একাধিক হিসাবের সঙ্গে মেলে"),
      supplier_collision: text(language, "The identity belongs to a supplier", "यह पहचान सप्लायर की है", "এই পরিচয় সরবরাহকারীর"),
      identity_collision: text(language, "The saved ID belongs to another customer", "सेव ID किसी दूसरे कस्टमर की है", "সেভ করা ID অন্য ক্রেতার"),
      duplicate_destination: text(language, "Two backup rows point to one customer", "दो बैकअप रिकॉर्ड एक कस्टमर पर जा रहे हैं", "দুটি ব্যাকআপ রেকর্ড একই ক্রেতার দিকে যাচ্ছে"),
    } satisfies Record<DuesRestoreReason, string>)[reason],
    ledgerReason: (reason: DuesLedgerRestoreReason) => ({
      new_customer: text(language, "New customer with complete history", "पूरा इतिहास वाला नया कस्टमर", "সম্পূর্ণ ইতিহাসসহ নতুন ক্রেতা"),
      matched_empty_customer: text(language, "Unique empty account matched", "एक खाली खाता मिला", "একটি খালি হিসাব মিলেছে"),
      same_archive_imported: text(language, "This exact archive was restored before", "यही आर्काइव पहले रिस्टोर हुआ", "এই একই আর্কাইভ আগে ফিরিয়ে আনা হয়েছে"),
      same_history_present: text(language, "The same complete history is already present", "यही पूरा इतिहास पहले से मौजूद है", "একই সম্পূর্ণ ইতিহাস আগেই আছে"),
      existing_history: text(language, "This account already has different financial history", "इस खाते में अलग फाइनेंशियल हिस्ट्री है", "এই হিসাবে অন্য আর্থিক ইতিহাস আছে"),
      ambiguous_identity: text(language, "Customer details match more than one account", "कस्टमर की डिटेल एक से ज्यादा खाते से मिलती है", "ক্রেতার তথ্য একাধিক হিসাবের সঙ্গে মেলে"),
      supplier_collision: text(language, "The identity belongs to a supplier", "यह पहचान सप्लायर की है", "এই পরিচয় সরবরাহকারীর"),
      identity_collision: text(language, "The saved identity belongs to another account", "सेव पहचान किसी दूसरे खाते की है", "সেভ পরিচয় অন্য হিসাবের"),
      record_collision: text(language, "A bill or payment ID already belongs to different data", "बिल या पेमेंट ID किसी अलग डेटा में मौजूद है", "বিল বা পেমেন্ট ID অন্য ডেটায় আছে"),
      invoice_number_collision: text(language, "An invoice number already belongs to another bill", "इनवॉइस नंबर किसी दूसरे बिल में मौजूद है", "ইনভয়েস নম্বর অন্য বিলে আছে"),
      duplicate_destination: text(language, "Two archive sections point to one customer", "दो आर्काइव सेक्शन एक कस्टमर पर जा रहे हैं", "দুটি আর্কাইভ বিভাগ একই ক্রেতার দিকে যাচ্ছে"),
    } satisfies Record<DuesLedgerRestoreReason, string>)[reason],
    error: (code: DuesBackupErrorCode | DuesLedgerErrorCode) => ({
      file_too_large: text(language, "This backup exceeds the safe file-size limit.", "यह बैकअप सुरक्षित फाइल सीमा से बड़ा है।", "ব্যাকআপটি নিরাপদ ফাইল সীমার বেশি।"),
      not_backup: text(language, "This is not an importable Midori Kanjo dues backup. Old statements, scans and arbitrary PDFs cannot be guessed safely.", "यह इम्पोर्ट होने वाला Midori Kanjo बाकी बैकअप नहीं है। पुराने स्टेटमेंट, स्कैन और दूसरी PDF का सुरक्षित अनुमान नहीं लगाया जाएगा।", "এটি ইমপোর্টযোগ্য Midori Kanjo বাকি ব্যাকআপ নয়। পুরোনো স্টেটমেন্ট, স্ক্যান বা অন্য PDF নিরাপদে অনুমান করা হবে না।"),
      duplicate_payload: text(language, "The file contains more than one restore payload and was rejected.", "फाइल में एक से ज्यादा रिस्टोर डेटा है, इसलिए इसे रोका गया।", "ফাইলে একাধিক ফিরিয়ে আনার তথ্য আছে, তাই এটি বাতিল হয়েছে।"),
      invalid_payload: text(language, "The backup contents are invalid or incomplete.", "बैकअप की सामग्री गलत या अधूरी है।", "ব্যাকআপের তথ্য ভুল বা অসম্পূর্ণ।"),
      unsupported_version: text(language, "This backup was made by a newer unsupported version.", "यह बैकअप नए असमर्थित वर्ज़न से बना है।", "এই ব্যাকআপ নতুন অসমর্থিত সংস্করণে তৈরি।"),
      wrong_currency: text(language, "Only INR dues backups can be restored.", "सिर्फ INR बाकी बैकअप रिस्टोर होगा।", "শুধু INR বাকি ব্যাকআপ ফিরিয়ে আনা যাবে।"),
      checksum_mismatch: text(language, "The embedded restore data failed its integrity check. It may be damaged or edited.", "अंदर का रिस्टोर डेटा इंटीग्रिटी जाँच में फेल हुआ। वह खराब या बदला हुआ हो सकता है।", "ভেতরের ফিরিয়ে আনার তথ্য ইন্টেগ্রিটি যাচাইয়ে ব্যর্থ হয়েছে। এটি ক্ষতিগ্রস্ত বা বদলানো হতে পারে।"),
      conflict: text(language, "The destination changed after review. Open the file and review it again.", "समीक्षा के बाद मौजूदा डेटा बदल गया। फाइल दोबारा खोलकर समीक्षा करें।", "পর্যালোচনার পরে বর্তমান তথ্য বদলেছে। ফাইল আবার খুলে দেখুন।"),
    } satisfies Record<DuesBackupErrorCode, string>)[code],
  };
}
