import type { Language } from "../lib/db";

export const festivalText = (language: Language, en: string, hi: string, bn: string) =>
  language === "hi" ? hi : language === "bn" ? bn : en;

export function festivalCopy(language: Language) {
  const text = (en: string, hi: string, bn: string) => festivalText(language, en, hi, bn);
  return {
    title: text("Season planner", "सीज़न प्लानर", "মরসুম পরিকল্পনা"),
    eyebrow: text("Festival calendar & stock planning", "त्योहार कैलेंडर और स्टॉक प्लानिंग", "উৎসবের ক্যালেন্ডার ও স্টক পরিকল্পনা"),
    backToItems: text("Back to products", "प्रोडक्ट पर वापस", "পণ্যে ফিরুন"),
    dashboard: text("Dashboard", "डैशबोर्ड", "ড্যাশবোর্ড"),
    calendar: text("Calendar", "कैलेंडर", "ক্যালেন্ডার"),
    tagging: text("Product tags", "प्रोडक्ट टैग", "পণ্যের ট্যাগ"),
    comparison: text("Year comparison", "साल की तुलना", "বছরের তুলনা"),
    leftovers: text("Leftovers", "बचा स्टॉक", "বেঁচে থাকা স্টক"),
    nextFestival: text("Next festival", "अगला त्योहार", "পরবর্তী উৎসব"),
    activeSeason: text("In season now", "अभी सीज़न में", "এখন মরসুম চলছে"),
    planningNow: text("Planning window open", "प्लानिंग शुरू", "পরিকল্পনার সময় শুরু"),
    startsIn: (days: number) => text(`Starts in ${days} day${days === 1 ? "" : "s"}`, `${days} दिन में शुरू`, `${days} দিনে শুরু`),
    endsIn: (days: number) => text(`Ends in ${days} day${days === 1 ? "" : "s"}`, `${days} दिन में खत्म`, `${days} দিনে শেষ`),
    planningStartsIn: (days: number) => text(`Stock planning starts in ${days} day${days === 1 ? "" : "s"}`, `स्टॉक प्लानिंग ${days} दिन में शुरू`, `স্টক পরিকল্পনা ${days} দিনে শুরু`),
    dateRange: text("Festival dates", "त्योहार की तारीख", "উৎসবের তারিখ"),
    salesWindow: text("Sales window", "बिक्री की अवधि", "বিক্রির সময়"),
    taggedProducts: text("Tagged products", "टैग किए प्रोडक्ट", "ট্যাগ করা পণ্য"),
    reorderPlan: text("Reorder suggestions", "दोबारा ऑर्डर सुझाव", "পুনরায় অর্ডারের পরামর্শ"),
    reorderHelp: text("Based on the last tracked season minus current counted stock. Suggestions never change stock or create a purchase order.", "पिछले रिकॉर्डेड सीज़न की बिक्री में से मौजूदा गिना हुआ स्टॉक घटाकर। सुझाव स्टॉक नहीं बदलते और खरीद ऑर्डर नहीं बनाते।", "গত রেকর্ড করা মরসুমের বিক্রি থেকে এখনকার গোনা স্টক বাদ দিয়ে। এই পরামর্শ স্টক বদলায় না বা ক্রয় অর্ডার বানায় না।"),
    lastSeason: text("Last season", "पिछला सीज़न", "গত মরসুম"),
    currentStock: text("Current stock", "मौजूदा स्टॉक", "বর্তমান স্টক"),
    suggestedOrder: text("Suggested order", "सुझाया ऑर्डर", "প্রস্তাবিত অর্ডার"),
    unknownStock: text("Count stock first", "पहले स्टॉक गिनें", "আগে স্টক গুনুন"),
    noHistory: text("No tracked prior season yet", "अभी पिछला रिकॉर्डेड सीज़न नहीं है", "এখনও আগের মরসুমের রেকর্ড নেই"),
    noHistoryDetail: text("This is new or untracked. The app will not invent zero sales.", "यह नया या बिना रिकॉर्ड का है। ऐप बिक्री को गलत तरीके से शून्य नहीं दिखाएगा।", "এটি নতুন বা এখনও ট্র্যাক করা হয়নি। অ্যাপ ভুল করে শূন্য বিক্রি দেখাবে না।"),
    oneYear: (year: number) => text(`Only ${year} has tracked invoice data, so there is not yet a meaningful year-over-year comparison.`, `सिर्फ ${year} का बिल डेटा है, इसलिए अभी सही साल-दर-साल तुलना नहीं बन सकती।`, `শুধু ${year}-এর বিলের তথ্য আছে, তাই এখনও অর্থপূর্ণ বছরভিত্তিক তুলনা করা যাবে না।`),
    historyYears: (years: string) => text(`Tracked seasons: ${years}`, `रिकॉर्डेड सीज़न: ${years}`, `রেকর্ড করা মরসুম: ${years}`),
    tasks: text("Season tasks", "सीज़न के काम", "মরসুমের কাজ"),
    orderStock: (name: string) => text(`Order ${name} stock`, `${name} का स्टॉक ऑर्डर करें`, `${name}-এর স্টক অর্ডার করুন`),
    due: text("due", "तय तारीख", "নির্ধারিত"),
    done: text("Done", "पूरा", "সম্পন্ন"),
    markDone: text("Mark done", "पूरा करें", "সম্পন্ন করুন"),
    overlapping: text("Overlapping planning windows", "एक साथ चल रही प्लानिंग", "একসঙ্গে চলা পরিকল্পনার সময়"),
    overlappingHelp: text("Several seasons can stay active together. Use each list independently, then review passed stock for put-away, discounting or holding.", "कई सीज़न एक साथ एक्टिव रह सकते हैं। हर लिस्ट अलग देखें, फिर बीते सीज़न का स्टॉक वापस रखने, छूट देने या अगले साल के लिए रखने के लिए देखें।", "একাধিক মরসুম একসঙ্গে সক্রিয় থাকতে পারে। প্রতিটি তালিকা আলাদাভাবে দেখুন, তারপর শেষ হওয়া মরসুমের মাল তুলে রাখা, ছাড় দেওয়া বা পরের বছরের জন্য রাখার সিদ্ধান্ত নিন।"),
    chooseFestival: text("Choose festival", "त्योहार चुनें", "উৎসব বাছুন"),
    chooseYear: text("Calendar year", "कैलेंडर साल", "ক্যালেন্ডার বছর"),
    leadTime: text("Lead time (weeks)", "पहले से तैयारी (हफ्ते)", "আগাম প্রস্তুতি (সপ্তাহ)"),
    startDate: text("Start date", "शुरू होने की तारीख", "শুরুর তারিখ"),
    endDate: text("End date", "खत्म होने की तारीख", "শেষের তারিখ"),
    names: text("Names & translations", "नाम और अनुवाद", "নাম ও অনুবাদ"),
    englishName: text("English name", "अंग्रेज़ी नाम", "ইংরেজি নাম"),
    hindiName: text("Hindi name", "हिंदी नाम", "হিন্দি নাম"),
    bengaliName: text("Bengali name", "बंगाली नाम", "বাংলা নাম"),
    saveDate: text("Save festival", "त्योहार सेव करें", "উৎসব সেভ করুন"),
    saved: text("Festival calendar saved on this device", "त्योहार कैलेंडर इस डिवाइस में सेव हुआ", "উৎসবের ক্যালেন্ডার এই ডিভাইসে সেভ হয়েছে"),
    saveFailed: text("Festival could not be saved", "त्योहार सेव नहीं हुआ", "উৎসব সেভ হয়নি"),
    verified: text("Verified seed", "जाँचा हुआ शुरुआती डेटा", "যাচাই করা প্রাথমিক তথ্য"),
    provisional: text("Provisional — review", "अस्थायी — जाँचें", "অস্থায়ী — যাচাই করুন"),
    businessEstimate: text("Business estimate — editable", "बिज़नेस अनुमान — बदल सकते हैं", "ব্যবসার আনুমানিক সময় — বদলানো যাবে"),
    verifiedSource: text("Initial date checked against the official calendar; review your shop's local observance.", "शुरुआती तारीख आधिकारिक कैलेंडर से जाँची गई है; अपनी दुकान के स्थानीय पालन के हिसाब से देख लें।", "প্রাথমিক তারিখ সরকারি ক্যালেন্ডারের সঙ্গে যাচাই করা হয়েছে; আপনার দোকানের স্থানীয় পালনের সঙ্গে মিলিয়ে নিন।"),
    provisionalSource: text("This lunar or regional date is provisional; review it before stock planning.", "यह चंद्र या क्षेत्रीय तारीख अस्थायी है; स्टॉक प्लानिंग से पहले जाँच लें।", "এই চন্দ্র বা আঞ্চলিক তারিখটি অস্থায়ী; স্টক পরিকল্পনার আগে যাচাই করুন।"),
    businessEstimateSource: text("This editable business planning estimate is stored on this device.", "यह बदलने योग्य बिज़नेस प्लानिंग अनुमान इस डिवाइस में सेव है।", "এই পরিবর্তনযোগ্য ব্যবসায়িক পরিকল্পনার আনুমানিক সময় এই ডিভাইসে সেভ আছে।"),
    calendarHelp: text("Dates are stored separately for each year. Editing a date immediately updates countdowns, sales windows, tasks and comparisons.", "हर साल की तारीख अलग सेव होती है। तारीख बदलते ही काउंटडाउन, बिक्री अवधि, काम और तुलना अपडेट होते हैं।", "প্রতিটি বছরের তারিখ আলাদাভাবে সেভ হয়। তারিখ বদলালেই কাউন্টডাউন, বিক্রির সময়, কাজ ও তুলনা আপডেট হয়।"),
    calendarSpectrum: text("Wide season calendar", "बड़ा सीज़न कैलेंडर", "বড় মরসুম ক্যালেন্ডার"),
    yearSpectrum: text("Twelve-month season spectrum", "बारह महीने का सीज़न व्यू", "বারো মাসের মরসুম দৃশ্য"),
    activeWindows: text("active windows", "चलती अवधियाँ", "সক্রিয় সময়"),
    previousMonth: text("Previous month", "पिछला महीना", "আগের মাস"),
    nextMonth: text("Next month", "अगला महीना", "পরের মাস"),
    monthView: text("Month view", "महीने का व्यू", "মাসের দৃশ্য"),
    today: text("Today", "आज", "আজ"),
    legend: text("Calendar colour guide", "कैलेंडर रंग गाइड", "ক্যালেন্ডারের রঙের নির্দেশিকা"),
    organizingPeriod: text("Organize & stock", "सामान लगाएँ और स्टॉक करें", "সাজান ও স্টক করুন"),
    festivalDates: text("Festival / puja dates", "त्योहार / पूजा की तारीखें", "উৎসব / পূজার তারিখ"),
    overlappingDates: text("Overlapping seasons", "एक साथ चलने वाले सीज़न", "একসঙ্গে চলা মরসুম"),
    selectedDate: text("Selected calendar date", "चुनी कैलेंडर तारीख", "বাছা ক্যালেন্ডার তারিখ"),
    closeDetails: text("Close calendar details", "कैलेंडर डिटेल बंद करें", "ক্যালেন্ডারের বিস্তারিত বন্ধ করুন"),
    noCalendarActivity: text("No festival planning or selling window is active on this date.", "इस तारीख पर कोई त्योहार प्लानिंग या बिक्री अवधि एक्टिव नहीं है।", "এই তারিখে কোনো উৎসব পরিকল্পনা বা বিক্রির সময় সক্রিয় নেই।"),
    organizingNow: text("Organizing period", "तैयारी की अवधि", "প্রস্তুতির সময়"),
    festivalNow: text("Festival in progress", "त्योहार चल रहा है", "উৎসব চলছে"),
    startOrganizing: text("Start organizing items", "आइटम लगाना शुरू करें", "পণ্য সাজানো শুরু করুন"),
    weeks: text("weeks", "हफ्ते", "সপ্তাহ"),
    editFestival: text("Edit this festival", "यह त्योहार बदलें", "এই উৎসব বদলান"),
    hideEditor: text("Hide editor", "एडिटर छिपाएँ", "এডিটর লুকান"),
    calendarSettings: text("Calendar settings", "कैलेंडर सेटिंग", "ক্যালেন্ডার সেটিংস"),
    calendarSettingsHelp: text("Open the full editor only when dates, names or lead time need changing.", "तारीख, नाम या तैयारी का समय बदलना हो तभी पूरा एडिटर खोलें।", "তারিখ, নাম বা আগাম সময় বদলানোর দরকার হলেই পুরো এডিটর খুলুন।"),
    editAllDates: text("Edit all festival dates", "सभी त्योहार तारीखें बदलें", "সব উৎসবের তারিখ বদলান"),
    hideAllDates: text("Hide date editors", "तारीख एडिटर छिपाएँ", "তারিখ এডিটর লুকান"),
    filterCategory: text("Category", "कैटेगरी", "ক্যাটাগরি"),
    allCategories: text("All categories", "सभी कैटेगरी", "সব ক্যাটাগরি"),
    searchProducts: text("Search product or SKU", "प्रोडक्ट या SKU खोजें", "পণ্য বা SKU খুঁজুন"),
    showTaggedOnly: text("Show tagged only", "सिर्फ टैग किए हुए", "শুধু ট্যাগ করা"),
    selectAllFiltered: (count: number) => text(`Select all ${count} filtered products`, `फ़िल्टर किए सभी ${count} प्रोडक्ट चुनें`, `ফিল্টার করা সব ${count}টি পণ্য বাছুন`),
    clearSelection: text("Clear selection", "चुनाव हटाएँ", "নির্বাচন সরান"),
    selected: (count: number) => text(`${count} selected`, `${count} चुने`, `${count}টি নির্বাচিত`),
    addTag: text("Add festival tag", "त्योहार टैग जोड़ें", "উৎসবের ট্যাগ যোগ করুন"),
    removeTag: text("Remove festival tag", "त्योहार टैग हटाएँ", "উৎসবের ট্যাগ সরান"),
    tagsSaved: (count: number) => text(`${count} products updated offline`, `${count} प्रोडक्ट ऑफलाइन अपडेट हुए`, `${count}টি পণ্য অফলাইনে আপডেট হয়েছে`),
    tagsSaveFailed: text("Product tags could not be saved", "प्रोडक्ट टैग सेव नहीं हुए", "পণ্যের ট্যাগ সেভ হয়নি"),
    noProducts: text("No products match this view", "इस व्यू में कोई प्रोडक्ट नहीं मिला", "এই তালিকায় কোনো পণ্য নেই"),
    showingFirst: (shown: number, total: number) => text(`Showing first ${shown} of ${total}; bulk actions still apply to every selected filtered product.`, `पहले ${shown} / ${total} दिख रहे हैं; बल्क एक्शन फिर भी चुने गए सभी फ़िल्टर प्रोडक्ट पर लगेगा।`, `প্রথম ${shown}/${total}টি দেখানো হচ্ছে; বাল্ক কাজ নির্বাচিত সব ফিল্টার করা পণ্যে প্রযোজ্য হবে।`),
    showMoreProducts: (count: number) => text(`Show next ${count}`, `अगले ${count} दिखाएँ`, `পরের ${count}টি দেখান`),
    itemComparison: text("By item", "आइटम के अनुसार", "পণ্য অনুযায়ী"),
    categoryComparison: text("By category", "कैटेगरी के अनुसार", "ক্যাটাগরি অনুযায়ী"),
    quantity: text("Sold", "बिका", "বিক্রি"),
    revenue: text("Revenue", "रेवेन्यू", "আয়"),
    noComparison: text("Not enough tracked seasons for comparison", "तुलना के लिए पर्याप्त रिकॉर्डेड सीज़न नहीं हैं", "তুলনার জন্য যথেষ্ট রেকর্ড করা মরসুম নেই"),
    partial: text("Current season is still in progress; its figures are partial.", "मौजूदा सीज़न अभी चल रहा है; इसके आंकड़े अधूरे हैं।", "বর্তমান মরসুম এখনও চলছে; এর হিসাব আংশিক।"),
    leftoverHelp: text("A product appears when stock traceable from season end remains above its low-stock threshold, or above zero when no threshold is set. Later inward receipts do not inflate it, and nothing is adjusted automatically.", "प्रोडक्ट तब दिखता है जब सीज़न खत्म होने से जुड़ा बचा स्टॉक उसकी कम-स्टॉक सीमा से ज्यादा हो, या सीमा न हो तो शून्य से ज्यादा हो। बाद की आवक इसमें नहीं जुड़ती और कुछ भी अपने-आप नहीं बदलता।", "মরসুম শেষের সময় থেকে হিসাব করা বাকি স্টক কম-স্টক সীমার বেশি হলে, অথবা সীমা না থাকলে শূন্যের বেশি হলে পণ্যটি দেখায়। পরে আসা মাল এতে যোগ হয় না এবং কিছুই নিজে থেকে বদলায় না।"),
    noLeftovers: text("No significant post-season leftovers right now", "अभी कोई बड़ा बचा हुआ सीज़न स्टॉक नहीं है", "এখন উল্লেখযোগ্য মরসুম-শেষের স্টক নেই"),
    putAway: text("Review: discount, push, put away or hold", "देखें: छूट, बिक्री बढ़ाएँ, वापस रखें या अगले साल तक रखें", "দেখুন: ছাড়, বিক্রি বাড়ানো, তুলে রাখা বা পরের বছরের জন্য রাখা"),
    threshold: text("Low-stock threshold", "कम-स्टॉक सीमा", "কম-স্টক সীমা"),
    noThreshold: text("No threshold", "कोई सीमा नहीं", "কোনো সীমা নেই"),
    value: text("Stock value", "स्टॉक वैल्यू", "স্টকের মূল্য"),
    missingCost: text("Purchase cost missing", "खरीद लागत नहीं है", "ক্রয়মূল্য নেই"),
    openDeadStock: text("Open dead-stock report", "डेड-स्टॉक रिपोर्ट खोलें", "ডেড-স্টক রিপোর্ট খুলুন"),
    daysPast: (days: number) => text(`${days} days after season end`, `सीज़न खत्म हुए ${days} दिन`, `মরসুম শেষ হয়েছে ${days} দিন`),
    allOffline: text("Calendar, tasks and analysis work fully offline", "कैलेंडर, काम और विश्लेषण पूरी तरह ऑफलाइन चलते हैं", "ক্যালেন্ডার, কাজ ও বিশ্লেষণ পুরোপুরি অফলাইনে চলে"),
    productFestivalTags: text("Festival tags", "त्योहार टैग", "উৎসবের ট্যাগ"),
    productFestivalHelp: text("Choose every season in which this product should appear.", "जिन सीज़न में यह प्रोडक्ट दिखना चाहिए, वे सभी चुनें।", "যে সব মরসুমে এই পণ্যটি দেখানো উচিত, সব বাছুন।"),
  };
}
